### 创建待办项
POST http://{{host}}/api/todos HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
  "todoItems": [
    {
      "content": "3",
      "expectTime": "{{$datetime iso8601 1 d}}"
    }
  ]
}


### 获取所有待办项
GET  http://{{host}}/api/todos HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

### 更新 单个待办项 的状态
PATCH  http://{{host}}/api/todos HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
  "todoIdArr": [
    "5ecf62a25e6b7025647e5bb9",
    "5ecf63d62cf4b632bcfe1438"
  ],
  "status": 1
}

### 更新单个/多个待办项 的状态
PATCH  http://{{host}}/api/todos HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
  "todoIdArr": [
    "5ecf62a25e6b7025647e5bb9",
    "5ecf63d62cf4b632bcfe1438"
  ],
  "status": 1
}